export type SystemPage = {
  slug: string;
  name: string;
  shortName: string;
  category: string;
  statement: string;
  description: string;
  accent: string;
  image?: string;
  appId?: string;
  branch: string;
  capabilities: string[];
  workflow: string[];
  teamRole: string;
  publicBoundary: string;
};

export const systems: SystemPage[] = [
  {
    slug: "router-systemmap",
    name: "Router / System Map",
    shortName: "Router",
    category: "Operating spine",
    statement: "See the whole system. Move through it in one tap.",
    description: "A metro-style map that turns apps, agents, queues, checks, relays, models, and automations into one legible control surface.",
    accent: "#56f0b2",
    image: "/apps/devices/systemmap.png",
    appId: "systemmap",
    branch: "codex/public/router-systemmap",
    capabilities: ["Visual system topology", "One-tap app routing", "Agent and automation state"],
    workflow: ["Read the network", "Spot active stations", "Open the right system"],
    teamRole: "A shared mental model for the entire PocketFlow installation.",
    publicBoundary: "The public map contains demonstration stations and sanitized state only.",
  },
  {
    slug: "baloss-llm",
    name: "Baloss LLM",
    shortName: "Baloss LLM",
    category: "Local intelligence",
    statement: "Small tasks stay close. Stronger reasoning wakes only when needed.",
    description: "The local model panel combines conversation, memory, tool routing, and system actions in a phone-native interface.",
    accent: "#7cf7c4",
    image: "/apps/devices/spino.png",
    appId: "spino",
    branch: "codex/public/baloss-llm",
    capabilities: ["Local-first conversation", "Model and tool routing", "Memory-aware actions"],
    workflow: ["Ask naturally", "Route by complexity", "Act across the shell"],
    teamRole: "A personal reasoning layer that can share a common operating vocabulary with the team.",
    publicBoundary: "No private model endpoints, account credentials, or personal memory are included.",
  },
  {
    slug: "builder",
    name: "Builder",
    shortName: "Builder",
    category: "Prompt architecture",
    statement: "Turn a messy idea into a buildable system.",
    description: "An offline-first workspace for breaking projects into boxes, files, agents, notes, contracts, and implementation handoffs.",
    accent: "#24df72",
    image: "/apps/devices/builder.png",
    appId: "builder",
    branch: "codex/public/builder",
    capabilities: ["Visual project decomposition", "Reusable architecture blocks", "Structured handoff packages"],
    workflow: ["Capture the project", "Connect the blocks", "Export the handoff"],
    teamRole: "A planning surface that gives humans and coding agents the same implementation map.",
    publicBoundary: "Example projects are synthetic and package exports contain no private workspace data.",
  },
  {
    slug: "archive-reader",
    name: "Archive / Reader",
    shortName: "Archive",
    category: "Local knowledge",
    statement: "Files become memory you can inspect.",
    description: "A calm file desk for imports, folders, previews, ZIP inspection, labels, metadata, and quarantine visibility.",
    accent: "#5be7b7",
    image: "/apps/devices/archive.png",
    appId: "archive",
    branch: "codex/public/archive-reader",
    capabilities: ["Local file import", "Rich preview and metadata", "ZIP and quarantine inspection"],
    workflow: ["Bring a file in", "Inspect it safely", "Keep it retrievable"],
    teamRole: "The shared memory shelf for plans, reports, source material, and generated outputs.",
    publicBoundary: "Browser-local sample storage replaces private phone databases and file paths.",
  },
  {
    slug: "memopad-calenotes",
    name: "MemoPad / Calenotes",
    shortName: "MemoPad",
    category: "Capture and action",
    statement: "Write once. Decide what it becomes later.",
    description: "A phone-native capture surface where a note can remain a note or become a task, list, reminder, or calendar event.",
    accent: "#ffd34e",
    image: "/apps/devices/notes.png",
    appId: "notes",
    branch: "codex/public/memopad-calenotes",
    capabilities: ["Fast mixed-format capture", "Task and calendar structure", "Natural-language intent"],
    workflow: ["Capture without friction", "Add structure", "Return when it matters"],
    teamRole: "A personal inbox that keeps small commitments visible without forcing one rigid workflow.",
    publicBoundary: "The public build uses demonstration notes and device-local browser state.",
  },
  {
    slug: "newsflow",
    name: "NewsFlow",
    shortName: "NewsFlow",
    category: "Research automation",
    statement: "From live signals to a structured briefing.",
    description: "A public-safe research and newsletter studio for collecting sources, shaping campaigns, composing editions, and scheduling work.",
    accent: "#f2ead7",
    image: "/apps/devices/news.png",
    appId: "news",
    branch: "codex/public/newsflow",
    capabilities: ["Research feed collection", "Campaign composition", "Scheduling and monitoring"],
    workflow: ["Pull the signal", "Shape the story", "Prepare the campaign"],
    teamRole: "A repeatable research-to-communication line that fits in a pocket.",
    publicBoundary: "Live recipient lists, delivery credentials, and sending are disabled in the public release.",
  },
  {
    slug: "notebook-agent",
    name: "Notebook / Moltbook Agent",
    shortName: "Moltbook",
    category: "Agent publishing",
    statement: "Give an agent a voice. Keep the controls in your hand.",
    description: "A red-and-black command surface for instructing an AI posting agent, managing cadence, and supervising its queue.",
    accent: "#ff3b30",
    image: "/apps/devices/moltbook.png",
    appId: "moltbook",
    branch: "codex/public/notebook-agent",
    capabilities: ["Natural-language agent policy", "Posting cadence controls", "Human-supervised queue"],
    workflow: ["Define the voice", "Set the rhythm", "Review before action"],
    teamRole: "A reusable template for visible, accountable agent-assisted publishing.",
    publicBoundary: "No account keys, live publishing credentials, or private posting history are present.",
  },
  {
    slug: "codex-relay",
    name: "Codex Relay",
    shortName: "Relay",
    category: "Phone-to-computer bridge",
    statement: "Carry the control surface. Leave the compute where it belongs.",
    description: "A relay cockpit for coordinating phone and desktop workflows, reviewing connection state, and handing work between surfaces.",
    accent: "#78c8ff",
    image: "/apps/devices/relay.png",
    appId: "relay",
    branch: "codex/public/codex-relay",
    capabilities: ["Bridge status and pairing", "Cross-device handoff", "Visible relay controls"],
    workflow: ["Pair the surfaces", "Send the intent", "Observe the handoff"],
    teamRole: "A lightweight bridge between mobile direction and workstation execution.",
    publicBoundary: "Private endpoints, chat history, pairing secrets, and active relay credentials are removed.",
  },
  {
    slug: "screen-relay",
    name: "Screen Relay",
    shortName: "Display",
    category: "Second screen",
    statement: "The right status, on the screen already beside you.",
    description: "A focused second-screen viewer for extending PocketFlow state onto another display without duplicating the entire workspace.",
    accent: "#4aa8ff",
    image: "/apps/devices/secondscreen.png",
    appId: "secondscreen",
    branch: "codex/public/screen-relay",
    capabilities: ["Second-screen pairing", "Connection visibility", "Focused remote display"],
    workflow: ["Choose a display", "Connect securely", "Keep status in sight"],
    teamRole: "A glanceable companion for monitoring work while the primary device stays free.",
    publicBoundary: "The public shell demonstrates pairing states without private streams or device identifiers.",
  },
  {
    slug: "terminal",
    name: "Terminal",
    shortName: "Terminal",
    category: "Developer operations",
    statement: "A serious command surface that fits on a phone.",
    description: "A multi-page terminal interface with command discovery, copy and paste tools, audit shortcuts, and a bridge-ready execution surface.",
    accent: "#00bdf2",
    image: "/apps/devices/terminal.png",
    appId: "terminal",
    branch: "codex/public/terminal",
    capabilities: ["Command finder", "Multiple terminal pages", "Audit and bridge controls"],
    workflow: ["Find the command", "Review the target", "Run from the pocket"],
    teamRole: "A mobile operations surface for developers who need control without reopening the laptop.",
    publicBoundary: "The public version is a safe shell and does not expose a private machine terminal.",
  },
  {
    slug: "pocketweb",
    name: "PocketWeb",
    shortName: "PocketWeb",
    category: "Web workspace",
    statement: "The web, shaped for the work in front of you.",
    description: "A lightweight browser workspace that keeps search, saved destinations, and focused web tasks inside the PocketFlow shell.",
    accent: "#4f8cff",
    image: "/apps/devices/pocketweb.png",
    appId: "pocketweb",
    branch: "codex/public/pocketweb",
    capabilities: ["Focused web navigation", "Saved work destinations", "Phone-native browsing controls"],
    workflow: ["Choose a destination", "Stay inside the task", "Return to the system"],
    teamRole: "A consistent doorway from local workflows to the public web.",
    publicBoundary: "No private browsing history, credentials, or internal bookmarks are included.",
  },
  {
    slug: "web-monitor",
    name: "Web Monitor",
    shortName: "Monitor",
    category: "Live visibility",
    statement: "Keep a public system in view without leaving PocketFlow.",
    description: "A cyan-on-black monitored web surface with reload, external-open, and sandboxed viewing controls.",
    accent: "#22d3ee",
    branch: "codex/public/web-monitor",
    capabilities: ["Sandboxed web view", "Fast refresh control", "External handoff"],
    workflow: ["Set the public target", "Monitor in place", "Open externally when needed"],
    teamRole: "A dedicated window for public dashboards, status pages, and monitored web tools.",
    publicBoundary: "The repository ships a public placeholder target instead of internal monitoring URLs.",
  },
];

export const githubBase = "https://github.com/RAVIZZA-VIBE-CODER/PocketFlowFinal";

export const systemBySlug = (slug: string) => systems.find((system) => system.slug === slug);
